name: coolduderules/wrangler
on:
  push:
  workflow_dispatch: # Fixed trigger
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  lint-file:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_FILE_IMAGE }} # Corrected variable syntax
    if: ${{ env.LINT_FILE_ALLOW_FAILURE == 'true' && env.LINT_FILE == 'true' || env.LINT_FILE == 'true' }}
    timeout-minutes: 60
    env:
      LINT_FILE_IMAGE: ${{ secrets.LINT_FILE_IMAGE }}
      LINT_FILE_ALLOW_FAILURE: ${{ secrets.LINT_FILE_ALLOW_FAILURE }}
      LINT_FILE: ${{ secrets.LINT_FILE }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: wget -q -O .Taskfile-lint.yml https://gitlab.com/op_so/task/task-templates/-/raw/main/Taskfile.d/lint.yml
    - run: echo -en "[safe]\n  directory = ${{ github.workspace }}\n" >> ~/.gitconfig
    - run: task --taskfile .Taskfile-lint.yml file

  lint-pre-commit:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_PRECOMMIT_IMAGE }} # Corrected variable syntax
    if: ${{ env.LINT_PRECOMMIT_ALLOW_FAILURE == 'true' && env.LINT_PRECOMMIT == 'true' || env.LINT_PRECOMMIT == 'true' }}
    timeout-minutes: 60
    env:
      LINT_PRECOMMIT_IMAGE: ${{ secrets.LINT_PRECOMMIT_IMAGE }}
      LINT_PRECOMMIT_ALLOW_FAILURE: ${{ secrets.LINT_PRECOMMIT_ALLOW_FAILURE }}
      LINT_PRECOMMIT: ${{ secrets.LINT_PRECOMMIT }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: task --taskfile /lint.yml pre-commit DIR=$(pwd)

  lint-docker:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_DOCKER_IMAGE }} # Corrected variable syntax
    if: ${{ env.LINT_DOCKER_ALLOW_FAILURE == 'true' && env.LINT_DOCKER == 'true' || env.LINT_DOCKER == 'true' }}
    timeout-minutes: 60
    env:
      LINT_DOCKER_IMAGE: ${{ secrets.LINT_DOCKER_IMAGE }}
      LINT_DOCKER_ALLOW_FAILURE: ${{ secrets.LINT_DOCKER_ALLOW_FAILURE }}
      LINT_DOCKER: ${{ secrets.LINT_DOCKER }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: hadolint $LINT_DOCKER_FILE

  lint-link:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_LINK_IMAGE }} # Corrected variable syntax
      options: "--entrypoint "
    if: ${{ env.LINT_LINK_ALLOW_FAILURE == 'true' && env.LINT_LINK == 'true' || env.LINT_LINK == 'true' }}
    timeout-minutes: 60
    env:
      LINT_LINK_IMAGE: ${{ secrets.LINT_LINK_IMAGE }}
      LINT_LINK_ALLOW_FAILURE: ${{ secrets.LINT_LINK_ALLOW_FAILURE }}
      LINT_LINK: ${{ secrets.LINT_LINK }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: lychee .

  lint-markdown:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_MARKDOWN_IMAGE }} # Corrected variable syntax
      options: "--entrypoint "
    if: ${{ env.LINT_MARKDOWN_ALLOW_FAILURE == 'true' && env.LINT_MARKDOWN == 'true' || env.LINT_MARKDOWN == 'true' }}
    timeout-minutes: 60
    env:
      LINT_MARKDOWN_IMAGE: ${{ secrets.LINT_MARKDOWN_IMAGE }}
      LINT_MARKDOWN_ALLOW_FAILURE: ${{ secrets.LINT_MARKDOWN_ALLOW_FAILURE }}
      LINT_MARKDOWN: ${{ secrets.LINT_MARKDOWN }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: markdownlint-cli2 $LINT_MARKDOWN_GLOB

  lint-shell:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_SHELL_IMAGE }} # Corrected variable syntax
    if: ${{ env.LINT_SHELL_ALLOW_FAILURE == 'true' && env.LINT_SHELL == 'true' || env.LINT_SHELL == 'true' }}
    timeout-minutes: 60
    env:
      LINT_SHELL_IMAGE: ${{ secrets.LINT_SHELL_IMAGE }}
      LINT_SHELL_ALLOW_FAILURE: ${{ secrets.LINT_SHELL_ALLOW_FAILURE }}
      LINT_SHELL: ${{ secrets.LINT_SHELL }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: shellcheck $LINT_SHELL_FILE

  lint-vale:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_VALE_IMAGE }} # Corrected variable syntax
      options: "--entrypoint "
    if: ${{ !(env.LINT_VALE != 'true') || env.LINT_VALE_ALLOW_FAILURE == 'true' }}
    timeout-minutes: 60
    env:
      LINT_VALE_IMAGE: ${{ secrets.LINT_VALE_IMAGE }}
      LINT_VALE_ALLOW_FAILURE: ${{ secrets.LINT_VALE_ALLOW_FAILURE }}
      LINT_VALE: ${{ secrets.LINT_VALE }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: mkdir -p $LINT_VALE_STYLES_DIR
    - run: "/bin/vale sync"
    - run: "/bin/vale $LINT_VALE_FILE"

  lint-yaml:
    runs-on: ubuntu-latest
    container:
      image: ${{ env.LINT_YAML_IMAGE }} # Corrected variable syntax
    if: ${{ env.LINT_YAML_ALLOW_FAILURE == 'true' && env.LINT_YAML == 'true' || env.LINT_YAML == 'true' }}
    timeout-minutes: 60
    env:
      LINT_YAML_IMAGE: ${{ secrets.LINT_YAML_IMAGE }}
      LINT_YAML_ALLOW_FAILURE: ${{ secrets.LINT_YAML_ALLOW_FAILURE }}
      LINT_YAML: ${{ secrets.LINT_YAML }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run: yamllint .

  docker-build:
    needs:
    - lint-file
    - lint-pre-commit
    - lint-docker
    - lint-link
    - lint-markdown
    - lint-shell
    - lint-vale
    - lint-yaml
    runs-on: ubuntu-latest
    container:
      image: ${{ env.DOCKER_IMAGE_FACTORY }} # Corrected variable syntax
    timeout-minutes: 60
    services:
      docker:
        image: docker:${{ env.DOCKER_SERVICE_DOCKER_TAG }} # Corrected variable syntax
    env:
      DOCKER_IMAGE_FACTORY: ${{ secrets.DOCKER_IMAGE_FACTORY }}
      DOCKER_SERVICE_DOCKER_TAG: ${{ secrets.DOCKER_SERVICE_DOCKER_TAG }}
      DOCKER_BUILD_VERSION: ${{ secrets.DOCKER_BUILD_VERSION }}
      CI_REGISTRY_IMAGE: ${{ secrets.CI_REGISTRY_IMAGE }}
      CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
      CI_REGISTRY_PASSWORD: ${{ secrets.CI_REGISTRY_PASSWORD }}
      COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
      COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      DOCKER_TASKFILE_DOCKER: ${{ secrets.DOCKER_TASKFILE_DOCKER }}
      DOCKER_TASKFILE_SBOM: ${{ secrets.DOCKER_TASKFILE_SBOM }}
      DOCKER_TASKFILE_VERSION: ${{ secrets.DOCKER_TASKFILE_VERSION }}
      DOCKER_REGISTRY_IMAGE_TAG: ${{ secrets.CI_REGISTRY_IMAGE }}/${{ github.ref }}:${{ github.sha }}
      DOCKER_DOCKERHUB_IMAGE_REPOSITORY: index.docker.io/jfxs/wrangler
      DOCKER_DOCKERHUB_RM_URL: jfxs/wrangler
      DOCKER_QUAY_IMAGE_REPOSITORY: quay.io/ifxs/wrangler
      DOCKER_QUAY_RM_URL: quay.io/ifxs/wrangler
      DOCKER_SBOM_SUBSET: "^ca-certificates |^curl |^git |^github.com/go-task/task/v3 |^node |^npm |^wrangler "
      LINT_DOCKER: true
      LINT_VALE: true
      TASKFILE_VERSION: ".Taskfile-version.yml"
      DOCKER_TEST_VERSION_DIND: false
      DOCKER_HOST: tcp://docker:2375
    steps:
    - uses: actions/checkout@v4.1.0
      with:
        fetch-depth: 20
        lfs: true
    - run:
        "!reference":
        - ".snippets"
        - prerequisites-task
    - run: if [ -z "$DOCKER_BUILD_VERSION" ]; then printf "\033[0;31m[ERROR] DOCKER_BUILD_VERSION variable is empty!\033[0m\n" && exit 1; fi
    - run: printf "\033[0;32m[OK] DOCKER_BUILD_VERSION \"%s\". \033[0m\n" "$DOCKER_BUILD_VERSION"
    - run: task --taskfile "$DOCKER_TASKFILE_DOCKER" build-push-multiarch DOCKER_USER="$CI_REGISTRY_USER" DOCKER_PASS="$CI_REGISTRY_PASSWORD" TAG="$DOCKER_REGISTRY_IMAGE_TAG" VERSION="$DOCKER_BUILD_VERSION"
    - run: digest=$(task --taskfile "$DOCKER_TASKFILE_DOCKER" get-digest IMG="$DOCKER_REGISTRY_IMAGE_TAG")
    - run: echo "$digest" > image-digest.txt
    - run: echo -n "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - run: if [ -z "$COSIGN_PASSWORD" ]; then printf "\033[0;31m[ERROR] COSIGN_PASSWORD variable is empty!\033[0m\n" && exit 1; fi
    - run: cosign sign --tlog-upload=false --key "$COSIGN_PRIVATE_KEY" "$CI_REGISTRY_IMAGE/${{ github.ref }}@$digest"
    - run: task --taskfile "$DOCKER_TASKFILE_SBOM" attach-sbom-attest I="$CI_REGISTRY_IMAGE/${{ github.ref }}@$digest" K="$COSIGN_PRIVATE_KEY"
    - run: docker logout "$CI_REGISTRY"
      if: always()
    - uses: actions/upload-artifact@v4.1.0
      if: success()
      with:
        name: "${{ github.job }}"
       
